### ISSUE TITLE
Errors running examples

### ISSUE THREAD

**Issue by chespinoza** [gdotdesign/elm-ui-examples#4]
I can't get the examples running, when try to run one of them, after installed the dependencies and running "elm-ui server" I get an error.

Node v6.9.1
Elm 0.18.0

```
You have errors in of your Elm file(s):
I cannot find module 'Tuple'.

Module 'Task.Extra' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```

**Comment by gdotdesign** [comment]
Thanks for opening this issue. 

I'm afraid I haven't update the examples to the latest versions of Elm and Elm-UI. I'l leave this open until they are updated and let you know.

**Comment by gdotdesign** [comment]
With the 1.0.0 release of Elm-UI the examples are updated and should be working properly. If for some reason they don't, feel free to reopen this issue.
