### ISSUE TITLE
Can any of these run without yarn?

### ISSUE THREAD

**Issue by wyattbenno777** [gdotdesign/elm-ui-examples#5]
I was looking at the example here.
http://elm-ui.info/documentation/guides/scrolling

I cannot find any reference on how to run these without yarn.

**Comment by gdotdesign** [comment]
You can run them with [npm](https://www.npmjs.com) as well: `npm install`, `npm run install` then `npm start` I've opted to display documentation for yarn because it's faster. 

As I've stated in the getting started guide you only need to install `elm-ui` in some way for your project after that it compiles like any other package. The dependencies these examples have are just there to run them easily and quickly.

**Comment by wyattbenno777** [comment]
Thanks. But I am still a bit lost.
I have this code in a Main.Elm file with the packages installed.
using the elm-install

I try elm-reactor and it shows module Ui.Button dependency not found.
Please share how I would start Main.elm with this file 
http://elm-ui.info/documentation/guides/scrolling
or how to compile it to js with elm-build.

Is this possible at this point?

**Comment by gdotdesign** [comment]
Here you go:

1 - elm-package.json:
```json
{
  "version": "1.0.0",
  "summary": "helpful summary of your project, less than 80 characters",
  "repository": "https://github.com/user/project.git",
  "license": "BSD3",
  "source-directories": [
    "."
  ],
  "exposed-modules": [
  ],
  "dependencies": {
    "gdotdesign/elm-ui": "1.0.1 <= v < 2.0.0",
    "elm-lang/core": "5.1.1 <= v < 6.0.0",
    "elm-lang/html": "2.0.0 <= v < 3.0.0",
    "elm-lang/dom": "1.1.1 <= v < 2.0.0"
  },
  "elm-version": "0.18.0 <= v < 0.19.0"
}
```

2 - Install dependencies with `elm-install`

3 - Main.elm
```elm
import Dom.Scroll
import Ui.Button
import Task
import Dom

import Html.Attributes exposing (style)
import Html exposing (div, text, span)

type alias Model =
  {}

init : Model
init =
  {}

type Msg
  = Scrolled (Result Dom.Error ())
  | ToTop

update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
  case msg of
    ToTop ->
      let
        task =
          Dom.Scroll.toTop "body"
      in
        ( model, Task.attempt Scrolled task )

    Scrolled _ ->
      ( model, Cmd.none )

view : {} -> Html.Html Msg
view model =
  div
  [ style
    [ ( "font-family", "sans" )
    , ( "margin", "40px" )
    ]
  ]
  [ span [ ] [ text "Scroll down and push the button!" ]
  , div
    [ style [ ( "padding-top", "1000px" ) ] ]
    [ Ui.Button.view ToTop
      { disabled = False
      , readonly = False
      , text = "To Top!"
      , kind = "primary"
      , size = "medium"
      }
    ]
  ]

main =
  Html.program
    { init = (init, Cmd.none)
    , update = update
    , view = view
    , subscriptions = \_ -> Sub.none
    }
```

4 - Html
```html
<html>
  <head>
  </head>
  <body id="body">
    <script type="text/javascript" src="index.js"></script>
    <script type="text/javascript">
      Elm.Main.fullscreen();
    </script>
  </body>
</html>
```

5 - Compile: `elm-make Main.elm --output index.js`

**Comment by wyattbenno777** [comment]
Thank you very much!
